name: Test

on: [push, pull_request]

jobs:
  setup:
    name: Ruby ${{ matrix.ruby }}

    runs-on: ubuntu-latest

    # Run this build only on either pull request or push.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository

    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

    steps:
      - run: sudo apt-get install at-spi2-core

      - uses: actions/checkout@v3

      - uses: hidakatsuya/action-setup-diff-pdf@v1
        with:
          diff-pdf-version: "0.5"

      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests for main
        run: bundle exec rake test:main

      - name: Run tests for basic report
        run: xvfb-run -a bundle exec rake test:basic_report

      - name: Run tests for section report
        run: xvfb-run -a bundle exec rake test:section_report
